services:
  mongodb:
    image: mongo:4.0.8
    container_name: poc_mongodb
    profiles:
      - all
      - mongodb
      - emulators
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: poc
      MONGO_INITDB_ROOT_PASSWORD: poc
      MONGO_INITDB_DATABASE: health-check
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - poc_mongodb_data:/data/db
    networks:
      - vksoftware

  mongo-express:
    image: mongo-express
    container_name: poc_mongodb_admin
    profiles:
      - all
      - mongodb
      - emulators
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula
      ME_CONFIG_MONGODB_URL: mongodb://poc:poc@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - vksoftware

  postgres:
    image: postgres
    container_name: poc_postgres
    profiles:
      - all
      - postgres
      - emulators
    volumes:
      - poc_postgres_data:/var/lib/postgresql/data
      - poc_postgres_backup:/backup
    environment:
      - POSTGRES_DB=poc
      - POSTGRES_USER=poc
      - POSTGRES_PASSWORD=poc
    ports:
      - "5432:5432"
    networks:
      - vksoftware

  pgadmin:
    image: dpage/pgadmin4
    container_name: poc_postgres_admin
    profiles:
      - all
      - postgres
      - emulators
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=poc@poc.com
      - PGADMIN_DEFAULT_PASSWORD=poc
    depends_on:
      - postgres
    networks:
      - vksoftware

  mysql:
    image: mysql:5.6
    container_name: poc_mysql
    profiles:
      - all
      - mysql
      - emulators
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=poc
    volumes:
      - poc_mysql_data:/var/lib/mysql
    networks:
      - vksoftware

  mysqladmin:
    image: phpmyadmin/phpmyadmin
    container_name: poc_mysql_admin
    profiles:
      - all
      - mysql
      - emulators
    ports:
      - "8083:80"
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - poc_mysql_admin:/etc/phpmyadmin
    depends_on:
      - mysql
    networks:
      - vksoftware

  sqlite-ui:
    image: coleifer/sqlite-web
    container_name: poc_sqlite_admin
    profiles:
      - all
      - sqlite
      - emulators
    ports:
      - "8086:8080"
    volumes:
      - ./assets/db:/data
    environment:
      - SQLITE_DATABASE=poc.sqlite

  redis:
    image: redis/redis-stack-server:latest
    container_name: poc_redis
    profiles:
      - all
      - redis
      - emulators
    # Save after 1hr if 1 write, after 5min if 100 writes, after 60 sec if 10000 writes
    environment:
      - REDIS_ARGS=--save 3600 1 --save 300 100 --save 60 10000
    ports:
      - 6379:6379
    volumes:
      - poc_redis_data:/data
    networks:
      - vksoftware

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: poc_redis_admin
    profiles:
      - all
      - redis
      - emulators
    ports:
      - 8084:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - vksoftware

  pubsub:
    image: google/cloud-sdk
    container_name: poc_pubsub
    profiles:
        - pubsub
        - emulators
        - all
    ports:
        - "8085:8085"
    command: gcloud beta emulators pubsub start --host-port=pubsub:8085
    networks:
        - vksoftware

  api:
    image: vksoftware/api:latest
    build: .
    container_name: api
    profiles:
      - all
      - api
    stdin_open: true
    tty: true
    command: >
      sh -c "
        pip install -r requirements.dev.txt
        uvicorn src.application.api.main:app --workers 1 --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/software
      - .ignore/site-packages:/opt/venv/lib/python3.10/site-packages
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=development
      - GOOGLE_CLOUD_PROJECT=vksoftware
      - GOOGLE_APPLICATION_CREDENTIALS=service_account.json
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - BUCKET_NAME=vksofware-documents
      - DB_CONNECTION_STRING=postgresql+psycopg2://poc:poc@postgres:5432/poc
      - TOPIC_ID=general-input
      - POKEAPI_URL=https://pokeapi.co/api/v2
      - CACHE_HOST=host.docker.internal
      - CACHE_PORT=6379
      - QTD_WORKERS=20
      - SUBSCRIPTION_ID=general-input-sub
      - MAX_MESSAGES=1
      - EVALUATE_MESSAGE_TIMEOUT=600
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=poc
      - POSTGRES_DB=poc
      - POSTGRES_PASSWORD=poc
      - PYTHONUNBUFFERED=1
      - TRACE=0
      - LOG_LEVEL=DEBUG
    networks:
      - vksoftware

networks:
  vksoftware:
    external: true

volumes:
  poc_mongodb_data:
  poc_postgres_data:
  poc_postgres_backup:
  poc_mysql_data:
  poc_mysql_admin:
  poc_redis_data:
  poc_sqlite_data:
